name: Test and Deploy Laravel Application

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, curl, zip
          ini-values: post_max_size=256M, upload_max_filesize=256M

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Set Env File
        run: cp .env.example .env
        
      - name: Set key
        run: php artisan key:generate

      - name: Create Database
        run: touch database/database.sqlite

      - name: Migrate Database
        run: php artisan migrate
        
      - name: Run tests
        run: php artisan test

  deploy:
    needs: run_tests
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, curl, zip
          ini-values: post_max_size=256M, upload_max_filesize=256M

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Set environment file
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "Using ${{ github.event.inputs.environment }} environment"
            cp .env.${{ github.event.inputs.environment }} .env
          else
            echo "Using production environment"
            cp .env.production .env
          fi

      - name: Deploy to Hetzner
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > private_key
          chmod 600 private_key
          rsync -avz --delete --exclude='.git*' --exclude='.env' -e "ssh -i private_key -o StrictHostKeyChecking=no" . $USERNAME@$HOST:/bookingsystem/
          ssh -i private_key -o StrictHostKeyChecking=no $USERNAME@$HOST "cd /bookingsystem && php artisan migrate --force && php artisan optimize"
