name: Auto Merge Bot

on:
  pull_request_target:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Auto Merge Bot
        uses: casassg/auto-merge-bot@v0.3
        with:
          merge_method: squash
          assign_reviewer: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
